# This file was generated by GoReleaser. DO NOT EDIT.
cask "apiary" do
  version "0.7.1"

  on_macos do
    on_intel do
      sha256 "f57ca77d147aab2da080671cfd119ac2baf83470ee6681327f5e123c36d997ae"
      url "https://github.com/orlandoburli/apiary/releases/download/v#{version}/apiary_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "019d329d507c6572d4d5290a9546ce6a9ca436254369801a30ec60a99a7fd01c"
      url "https://github.com/orlandoburli/apiary/releases/download/v#{version}/apiary_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "2a26492a11769a8e723bed0e6e77d77168dc115bfa7022e1f0da2cbc5c813923"
      url "https://github.com/orlandoburli/apiary/releases/download/v#{version}/apiary_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "ff413ab980e7bb2280fa765cd760623ae33ad872789f3fd1119ea5ed8e3429ea"
      url "https://github.com/orlandoburli/apiary/releases/download/v#{version}/apiary_#{version}_linux_arm64.tar.gz"
    end
  end

  name "apiary"
  desc "Task-driven agent orchestration harness (GitHub Issues, Plane, and other sources)."
  homepage "https://github.com/orlandoburli/apiary"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "apiary"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/apiary"]
    end
  end

  # No zap stanza required

end
