# This file was generated by GoReleaser. DO NOT EDIT.
cask "apiary" do
  version "0.12.0"

  on_macos do
    on_intel do
      sha256 "c03058cd19fa217961a0e266d7c3b6bc44c504bad5af8e4688611ed65a75a2d2"
      url "https://github.com/orlandoburli/apiary/releases/download/v#{version}/apiary_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "571d3d739a5528ee80d11015914bf3b3dc6b1f94b40c83990aac439e17a5e2db"
      url "https://github.com/orlandoburli/apiary/releases/download/v#{version}/apiary_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "70ee5f3c235cd7ec695dce5b0b7ed8e8fd4d0bab89226a5116e3d6d9a521cd1f"
      url "https://github.com/orlandoburli/apiary/releases/download/v#{version}/apiary_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "d0ecf1999c7663d3509e47d42dfb3d8705ba3e701f65b20d98e6c7ea263ff2c5"
      url "https://github.com/orlandoburli/apiary/releases/download/v#{version}/apiary_#{version}_linux_arm64.tar.gz"
    end
  end

  name "apiary"
  desc "Task-driven agent orchestration harness (GitHub Issues, Plane, and other sources)."
  homepage "https://github.com/orlandoburli/apiary"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "apiary"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/apiary"]
    end
  end

  # No zap stanza required

end
