# This file was generated by GoReleaser. DO NOT EDIT.
cask "apiary" do
  version "0.21.0"

  on_macos do
    on_arm do
      sha256 "bd1e8c626ada1a29471d880cee9f9f6ca0b8812356a0e563689fd87a91187a40"
      url "https://github.com/orlandoburli/apiary/releases/download/v#{version}/apiary_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "787f91ea3be052cce87a9de623b395e8ccfddceca172525dd36d763d0eb828a2"
      url "https://github.com/orlandoburli/apiary/releases/download/v#{version}/apiary_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "44aeb97df577df9e3207db846ab156fa5db1d0ced022fb910f78aca6d661bc17"
      url "https://github.com/orlandoburli/apiary/releases/download/v#{version}/apiary_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "d975c938fa166e73967764de0a7b03125aae991ca24a5c321fe44edf2bca1135"
      url "https://github.com/orlandoburli/apiary/releases/download/v#{version}/apiary_#{version}_linux_amd64.tar.gz"
    end
  end

  name "apiary"
  desc "Task-driven agent orchestration harness (GitHub Issues, Plane, and other sources)."
  homepage "https://github.com/orlandoburli/apiary"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "apiary"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/apiary"]
    end
  end

  # No zap stanza required
end
